### ISSUE TITLE
Typo of source strings

### ISSUE THREAD

**Issue by Dafrok** [nohello-net/site#24]
Found some typo of source strings, but I've no permission to fix it.

Line 10: sophie -> Sophie
Line 16: taht -> that

**Comment by Dafrok** [comment]
Btw, zh_CN is ready for launch

**Comment by Dafrok** [comment]
There's another question, zh-Hans and zh-CN is almost the same. Do I need to copy zh-CN for translation of zh-Hans?

**Comment by doceazedo** [comment]
The line 10 is all lowercase, so that's most likely not a typo. The line 16 has a note saying that the typo is intentional.

**Comment by notjosh** [comment]
> Found some typo of source strings, but I've no permission to fix it.

They're intentional, but thanks for checking!

> Btw, zh_CN is ready for launch

Cool! I've just updated a string to remove the year substitution - hopefully that makes translations easier for you & others! So if you update that one, I can add it to the site.

> There's another question, zh-Hans and zh-CN is almost the same. Do I need to copy zh-CN for translation of zh-Hans?

That's a good question, and you probably know more than I do! What is normally done there? I'm ok with you copying it over - I believe that's how Transifex would do it.

**Comment by Dafrok** [comment]
@notjosh  Thanks for reply. But I wonder how can I translate this substitution?
"not 1990" in Chinese is "不是 1990 年"，It cannot simply replace with that substitution mark.

**Comment by Dafrok** [comment]
Anyway I've resolved it.

**Comment by Dafrok** [comment]
Any update?

**Comment by notjosh** [comment]
zh-cn is shipped! https://nohello.net/zh-cn/ 🥳
